SERVER_NAME?=fat32drv
BINARY?=$(SERVER_NAME)

BINARY_OBJS=main.o

# The following C defines are recognised by fat32drv and enable various things
#
#	DEBUG_FAT32				Enable FAT32 debug output
#	DEBUG_FAT32_IO			Enable storage I/O debug output
#
CDEFS=

include ../server_common.mk