SERVER_NAME?=devman
BINARY?=$(SERVER_NAME)

BINARY_OBJS=main.o

# The following C defines are recognised by devman and enable various things
#
#	DEBUG_ACPI				Dump **lots** of info about ACPI tables
#	DEBUG_PCI				Dump info about PCI drivers that are spawned
#	DEBUG_PCI_MCFG			Dump info about the MCFG ACPI table
#
CDEFS=

include ../server_common.mk
