# GUI Compositor Server Makefile

SERVER_NAME?=kterminal
BINARY?=$(SERVER_NAME)

BINARY_OBJS=gdebugterm.o main.o

# The following C defines are recognised by kterminal and enable various things
#
#	USE_BIZCAT_FONT			Use BIZCAT font instead of the default
#
CDEFS=

include ../server_common.mk
