;
; stage3 - MSI interrupt dispatchers
; anos - An Operating System
;
; Copyright (c) 2025 Ross Bamford
;

bits 64

%include "kernel/arch/x86_64/isr_common.asm"

global msi_generic_handler
extern msi_handle_interrupt

section .text

msi_generic_handler:

    ; NOTE: Minor weirdness here - although this is an IRQ handler, by the
    ;       time we get here we've pushed the vector number, so we need to
    ;       use the trap_with_code conditional swap, which adds an extra
    ;       8 bytes to the stack offset to account for that...

    trap_conditional_swapgs_with_code       ; Switch to kernel GS if needed
    pusha_sysv                              ; Push all caller-saved regs

    mov rdi, pusha_sysv_arg0[rsp]           ; Get vector number from stack (pushed by specific ISR below)
    xor rsi, rsi                            ; data=0 for now
    
    call msi_handle_interrupt               ; actual handler

    popa_sysv                               ; Restore regs
    trap_conditional_swapgs_with_code       ; Switch GS back if needed

    add rsp, 8                              ; remove vector number
    iretq

%macro MSI_HANDLER 1
global msi_handler_%1
msi_handler_%1:
    push %1                                 ; Push vector number
    jmp msi_generic_handler                 ; Jump to handler 👆
%endmacro

MSI_HANDLER 0x40
MSI_HANDLER 0x41
MSI_HANDLER 0x42
MSI_HANDLER 0x43
MSI_HANDLER 0x44
MSI_HANDLER 0x45
MSI_HANDLER 0x46
MSI_HANDLER 0x47
MSI_HANDLER 0x48
MSI_HANDLER 0x49
MSI_HANDLER 0x4A
MSI_HANDLER 0x4B
MSI_HANDLER 0x4C
MSI_HANDLER 0x4D
MSI_HANDLER 0x4E
MSI_HANDLER 0x4F
MSI_HANDLER 0x50
MSI_HANDLER 0x51
MSI_HANDLER 0x52
MSI_HANDLER 0x53
MSI_HANDLER 0x54
MSI_HANDLER 0x55
MSI_HANDLER 0x56
MSI_HANDLER 0x57
MSI_HANDLER 0x58
MSI_HANDLER 0x59
MSI_HANDLER 0x5A
MSI_HANDLER 0x5B
MSI_HANDLER 0x5C
MSI_HANDLER 0x5D
MSI_HANDLER 0x5E
MSI_HANDLER 0x5F
MSI_HANDLER 0x60
MSI_HANDLER 0x61
MSI_HANDLER 0x62
MSI_HANDLER 0x63
MSI_HANDLER 0x64
MSI_HANDLER 0x65
MSI_HANDLER 0x66
MSI_HANDLER 0x67
MSI_HANDLER 0x68
MSI_HANDLER 0x69
MSI_HANDLER 0x6A
MSI_HANDLER 0x6B
MSI_HANDLER 0x6C
MSI_HANDLER 0x6D
MSI_HANDLER 0x6E
MSI_HANDLER 0x6F
MSI_HANDLER 0x70
MSI_HANDLER 0x71
MSI_HANDLER 0x72
MSI_HANDLER 0x73
MSI_HANDLER 0x74
MSI_HANDLER 0x75
MSI_HANDLER 0x76
MSI_HANDLER 0x77
MSI_HANDLER 0x78
MSI_HANDLER 0x79
MSI_HANDLER 0x7A
MSI_HANDLER 0x7B
MSI_HANDLER 0x7C
MSI_HANDLER 0x7D
MSI_HANDLER 0x7E
MSI_HANDLER 0x7F
MSI_HANDLER 0x80
MSI_HANDLER 0x81
MSI_HANDLER 0x82
MSI_HANDLER 0x83
MSI_HANDLER 0x84
MSI_HANDLER 0x85
MSI_HANDLER 0x86
MSI_HANDLER 0x87
MSI_HANDLER 0x88
MSI_HANDLER 0x89
MSI_HANDLER 0x8A
MSI_HANDLER 0x8B
MSI_HANDLER 0x8C
MSI_HANDLER 0x8D
MSI_HANDLER 0x8E
MSI_HANDLER 0x8F
MSI_HANDLER 0x90
MSI_HANDLER 0x91
MSI_HANDLER 0x92
MSI_HANDLER 0x93
MSI_HANDLER 0x94
MSI_HANDLER 0x95
MSI_HANDLER 0x96
MSI_HANDLER 0x97
MSI_HANDLER 0x98
MSI_HANDLER 0x99
MSI_HANDLER 0x9A
MSI_HANDLER 0x9B
MSI_HANDLER 0x9C
MSI_HANDLER 0x9D
MSI_HANDLER 0x9E
MSI_HANDLER 0x9F
MSI_HANDLER 0xA0
MSI_HANDLER 0xA1
MSI_HANDLER 0xA2
MSI_HANDLER 0xA3
MSI_HANDLER 0xA4
MSI_HANDLER 0xA5
MSI_HANDLER 0xA6
MSI_HANDLER 0xA7
MSI_HANDLER 0xA8
MSI_HANDLER 0xA9
MSI_HANDLER 0xAA
MSI_HANDLER 0xAB
MSI_HANDLER 0xAC
MSI_HANDLER 0xAD
MSI_HANDLER 0xAE
MSI_HANDLER 0xAF
MSI_HANDLER 0xB0
MSI_HANDLER 0xB1
MSI_HANDLER 0xB2
MSI_HANDLER 0xB3
MSI_HANDLER 0xB4
MSI_HANDLER 0xB5
MSI_HANDLER 0xB6
MSI_HANDLER 0xB7
MSI_HANDLER 0xB8
MSI_HANDLER 0xB9
MSI_HANDLER 0xBA
MSI_HANDLER 0xBB
MSI_HANDLER 0xBC
MSI_HANDLER 0xBD
MSI_HANDLER 0xBE
MSI_HANDLER 0xBF
MSI_HANDLER 0xC0
MSI_HANDLER 0xC1
MSI_HANDLER 0xC2
MSI_HANDLER 0xC3
MSI_HANDLER 0xC4
MSI_HANDLER 0xC5
MSI_HANDLER 0xC6
MSI_HANDLER 0xC7
MSI_HANDLER 0xC8
MSI_HANDLER 0xC9
MSI_HANDLER 0xCA
MSI_HANDLER 0xCB
MSI_HANDLER 0xCC
MSI_HANDLER 0xCD
MSI_HANDLER 0xCE
MSI_HANDLER 0xCF
MSI_HANDLER 0xD0
MSI_HANDLER 0xD1
MSI_HANDLER 0xD2
MSI_HANDLER 0xD3
MSI_HANDLER 0xD4
MSI_HANDLER 0xD5
MSI_HANDLER 0xD6
MSI_HANDLER 0xD7
MSI_HANDLER 0xD8
MSI_HANDLER 0xD9
MSI_HANDLER 0xDA
MSI_HANDLER 0xDB
MSI_HANDLER 0xDC
MSI_HANDLER 0xDD
MSI_HANDLER 0xDE
MSI_HANDLER 0xDF