name: compile_and_test

on:
  push:
    branches: [ main ]
    paths-ignore:
<<<<<<< HEAD
<<<<<<< HEAD
      - "**/coverage.svg"
=======
          - "**/coverage.svg"
>>>>>>> b22406e (Try add coverage badge)
=======
      - "**/coverage.svg"
>>>>>>> 24434b2 (Fixes)
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**/coverage.svg"

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  macos_arm_build_and_test:
    name: Build & test (macOS / ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          brew install nasm clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test
        shell: bash
  macos_x64_build_and_test:
    name: Build & test (macOS / x86_64)
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          brew install nasm clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test
        shell: bash
  linux_build_and_test:
    name: Build & test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          sudo apt-get install nasm lcov
          pip install clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test coverage
        shell: bash
<<<<<<< HEAD

<<<<<<< HEAD
      - name: Coverage Badge
        uses: ImBIOS/lcov-coverage-badge@v1
        with:
          file: ./gcov/kernel/coverage.info

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ./gcov/kernel/coverage.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
      
=======
      - name: Coverage badge
        uses: GoogleCloudPlatform/lcov-coverage-badge@v1.0.0
        file: ./gcov/kernel/coverage.info
>>>>>>> b22406e (Try add coverage badge)
=======
>>>>>>> 7fe9dc0 (Moar fixes)
