name: compile_and_test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  macos_arm_build_and_test:
    name: Build & test (macOS / ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          brew install nasm clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test
        shell: bash
  macos_x64_build_and_test:
    name: Build & test (macOS / x86_64)
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          brew install nasm clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test
        shell: bash
  linux_build_and_test:
    name: Build & test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          sudo apt-get install nasm
          pip install clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test
        shell: bash
