name: compile_and_test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/coverage.svg"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**/coverage.svg"

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  macos_arm_build_and_test:
    name: Build & test (macOS / ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          brew update
          brew install nasm clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test
        shell: bash
  macos_x64_build_and_test:
    name: Build & test (macOS / x86_64)
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          brew update
          brew install nasm clang-format
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test
        shell: bash
  linux_build_and_test:
    name: Build & test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          sudo apt-get update
          sudo apt-get install nasm lcov
          pip install clang-format==20.1.4
          find . -name '*.c' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          find . -name '*.h' -print0 | xargs -0 clang-format -dry-run -style=file -Werror
          make clean test coverage
        shell: bash

      - name: Make coverage paths relative
        run: |
          sed -i.tmp "s;$PWD/;;g" gcov/kernel/coverage*.info
          sed -i.tmp "s;$PWD/;;g" gcov/system/coverage*.info
          sed -i.tmp "s;$PWD/;;g" gcov/pcidrv/coverage*.info
          sed -i.tmp "s;$PWD/;;g" gcov/ahcidrv/coverage*.info
        shell: bash

      - name: Make merged coverage files
        run: |
          lcov --add-tracefile gcov/kernel/coverage.info --add-tracefile gcov/system/coverage.info --add-tracefile gcov/pcidrv/coverage.info --add-tracefile gcov/ahcidrv/coverage.info -o gcov/all.info
          lcov --add-tracefile gcov/system/coverage.info --add-tracefile gcov/pcidrv/coverage.info --add-tracefile gcov/ahcidrv/coverage.info -o gcov/userspace.info

      - name: Kernel Coverage Badge
        uses: ImBIOS/lcov-coverage-badge@v1
        with:
          label: "Overall Coverage"
          file: ./gcov/all.info
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report overall code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          title-prefix: "Overall"
          coverage-files: ./gcov/all.info
          artifact-name: overall-code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report kernel code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          title-prefix: "Kernel"
          coverage-files: ./gcov/kernel/coverage.info
          artifact-name: kernel-code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report system code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          title-prefix: "Userspace"
          coverage-files: ./gcov/userspace.info
          artifact-name: userspace-code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

