name: compile_and_test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  macos_build_and_test:
    name: Build & test (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          brew install nasm
          make clean test
        shell: bash


  linux_build_and_test:
    name: Build & test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & run tests
        run: |
          sudo apt-get install nasm
          HOST_ARCH=elf64 make clean test
        shell: bash
